# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler for multivariate normal distribution using Rcpp
#' @description A Gibbs sampler for multivariate normal distribution using Rcpp
#' @param m the number of samples
#' @param x0 the initial value
#' @param mu the mean vector of the distribution
#' @param sigma the covariance matrix of the distribution
#' @return a MCMC chain \code{n}
#' @examples
#' \dontrun{
#' a<-rmnGibbsc(2, c(1,2,3),c(0,0,0),matrix(c(1,0.5,0.5,0.5,1,0.5,0.5,0.5,1),3,3))
#' a
#' }
#' @export
rmnGibbsc <- function(m, x0, mu, sigma) {
    .Call('_SA23204191_rmnGibbsc', PACKAGE = 'SA23204191', m, x0, mu, sigma)
}

